spring.application.name=APIGateway
server.port=9000
spring.cloud.server.eureka-server=http://localhost:8761/eureka/
spring.cloud.server.register-with-eureka=true
spring.cloud.server.fetch-registry= true

spring.cloud.gateway.server.webflux.routes[0].id=StaffManagement
spring.cloud.gateway.server.webflux.routes[0].uri=lb://
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/staff/**