package com.rainbowhospitals.enums;

public enum Specialization {
	GENERAL_PHYSICIAN,CARDIOLOGIST,NEUROLOGIST,ENT_SPECIALIST,DENTIST,HEMATOLOGISTS,PULMONOLOGIST,RECEPTIONIST,OTHERS,GASTROENTEROLOGIST,PEDIATRICIAN,GYNECOLOGIST;
}
